<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
<nav style="display: flex; gap: 20px;">

<a href="home">home</a>
<a href="catalogo">catalogo</a>
<a href="juego">buscar juego</a>
<a href="categorias">categorias</a>
<a href="categoria">categoria especifica</a>


</nav>
