<form method='post' action='login'>
<input type="hidden" name="action" value="login"> 
    <div class='form-group'>
        <label for='email'>Email</label>
        <input type='email' class='form-control' id='email' name='email' required>
    </div>
    <div class='form-group'>
        <label for='password'>Password</label>
        <input type='password' class='form-control' id='password' name='password' required>
    </div>
    <button type='submit' class='btn btn-primary'>Login</button>
</form>


