<div style="display:flex">
    <ul>
        <?php foreach($juegos as $juego): ?>
        <li><h3>ID:<?=$juego->ID?>, juego: <?=$juego->nombre?></h3></li>
        <?php endforeach ?>
    </ul>

    <ul>
        <?php foreach($consolas as $consola): ?>
        <li><h3>ID:<?=$consola->ID?>, consola: <?=$consola->nombre?></h3></li>
        <?php endforeach ?>
    </ul>
</div>
<form action="updateConsola" method="post" enctype="multipart/form-data">
<input type="hidden" name="action" value="updatejuego"> 
        <input type="number" name="ID" placeholder="inserte ID de articulo que desea modificar">
        <br><br>
        <input type="text" name="nombre" placeholder="nombre">
        <input type="text" name="fecha_lanzamiento" placeholder="fecha de lanzamiento">
        <input type="text" name="jugadores" placeholder="jugadores">
        
        <input type="text" name="ID_consola" placeholder="inserte el id de la consola a la que correspondonde">
        
        
        <input type="file" name="input_name" id="imageToUpload">
        <br>
        <button type="submit">modificar</button>

   

</form>