<ul>
    <?php foreach($consolas as $consola): ?>
       <li><h3>ID:<?=$consola->ID?>, consola: <?=$consola->nombre?></h3></li>
    <?php endforeach ?>
</ul>

<form action="updateConsola" method="post">
    <input type="hidden" name="action" value="updateconsola"> 
        <input type="number" name="ID" placeholder="inserte ID de articulo que desea modificar">
        <br><br>
        <input type="text" name="nombre" placeholder="nuevo nombre">
        <input type="text" name="marca" placeholder="nueva marca">
        <input type="text" name="color" placeholder="nuevo color">
        <input type="text" name="generacion" placeholder="nueva generacion">
        <br>
        <button type="submit">modificar</button>

</form>