<h1> ELIMINAR CONSOLAS</h1>
<table class="table">
    <thead>
    <tr>
        <th scope="col">ID</th>
      <th scope="col">NOMBRE</th>
      <th scope="col">MARCA</th>
      <th scope="col">COLOR</th>
      <th scope="col">GENERACION</th>
      
    </tr>
</thead>
  <tbody>
    <?php
    
     foreach($consolas as $consola) {
        echo "<tr>";
        echo "<td>" . $consola->ID  ."</td>";
        echo  "<td>" . $consola->nombre . "</td>";
        echo "<td>" . $consola->marca. "</td>";
        echo "<td>" . $consola->color ."</td>";
        echo "<td>" . $consola->generacion . "</td>";
       
        
     }
     
     ?>


<form action="deleteconsola" method="post">
<input type="hidden" name="action" value="deleteConsola">
  
    <input type="text" name="ID" placeholder="insertar id a borrar">
    <button type="submit">borrar</button>
</form>