<div class="container py-1">

    <button id="btnAgregarCategoria" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#miModalCategoria">AGREGAR CATEGORÍA</button>

    <div class="modal fade" id="miModalCategoria">

        <div class="modal-dialog modal-dialog-scrollable">

            <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title">FORMULARIO DE CATEGORÍAS</h5>

                    <button class="btn-close" data-bs-dismiss="modal">X</button>
                </div>

                <div class="modal-body">
                    <form class="form-container" action='' method='POST'>
                        <div class="mb-3">
                            <label for="nombreCategoria" class="form-label">Nombre de la categoría</label>
                            <input type="text" class="form-control" id="nombreCategoria" name="nombreCategoria">
                        </div>

                        <div class="mb-3">
                            <label for="marcaCategoria" class="form-label">Marca:</label>
                            <input type="text" class="form-control" id="marcaCategoria" name="marcaCategoria">
                        </div>

                        <div class="mb-3">
                            <label for="color" class="form-label">Color de la consola:</label>
                            <input type="text" class="form-control" id="colorConsola" name="colorConsola">
                        </div>

                        <div class="mb-3">
                            <label for="generacionCategoria" class="form-label">Generación:</label>
                            <input type="text" class="form-control" id="generacionConsola" name="generacionConsola">
                        </div>

                        <div class="mb-3 form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
                            <label class="form-check-label" for="exampleCheck1">Check me out</label>
                        </div>
                        <button type="submit" class="btn btn-success">ENVIAR</button>
                </div>

                <div class="modal-footer">
                    <button class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
                    <button class="btn btn-primary">Guardar</button>
                </div>

            </div>

        </div>

    </div>

</div>