<h1>AGREGAR CONSOLA</h1>
<form action="addconsola" method="POST">
<input type="hidden" name="action" value="addconsola"> 

    <input type="text" name="nombreCategoria" placeholder="insertar nombre de consola">
    <input type="text" name="marca" placeholder="insertar marca de consola">
    <input type="text" name="color" placeholder="insertar color de consola">
    <input type="text" name="generacion" placeholder="insertar generacion de consola">

    <button type="submit">agregar</button>

</form>