<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="css/estilos.cssstyle">
    <link rel="stylesheet" href="css/estilos.css">   <link rel="stylesheet" href="../css/estilos.css">
 <script src="https://kit.fontawesome.com/767382d03b.js" crossorigin="anonymous"></script>
</head>
<body>
    
<section>
    <h1 id="main-title">CATÁLOGO CRUD0</h1>
</section>
<nav style="display: flex; gap: 20px;">
    <ul style="display: flex;">
        <li><a href="home">home</a></li>
        
        <ul>
            <li><a href="catalogo">catalogo</a></li>
            <li><a href="categorias">categorias</a></li> 
            
        </ul>

   
    </ul>
     <ul>
            <li><a href="addJuego">agregar juego</a></li>
            <li><a href="addConsola">agregar consola</a></li>
            <li><a href="updateConsola">modificar consola</a></li>
            <li><a href="updateJuego">modificar juego</a></li>
        </ul>
</nav>
