

<style>
    body {
        font-family: Arial, sans-serif;
        text-align: center;
        padding: 50px;
        background-color: #f4f4f4;
    }

    h1 {
        font-size: 50px;
        color: #ff0000;
    }

    p {
        font-size: 20px;
    }

    a {
        text-decoration: none;
        color: #007bff;
    }

    a:hover {
        text-decoration: underline;
    }
</style>
</head>

<body>
    <h1>Error 404</h1>
    <p>Lo sentimos, la página que estás buscando no existe.</p>
    <p><a href="/home">Volver a la página de inicio</a></p>

    <body>