

 <img src="<?= $juego->imagen; ?>" alt="<?= $juego->nombre; ?>" style="width: 200px;">
    <?php
  
    echo "<tr>";
    echo "<td>" . $juego->ID. "</td>";
    echo "<td>" . $juego->nombre . "</td>";
    echo "<td>" . $juego->fecha_lanzamiento . "</td>";
    echo "<td>" . $juego->jugadores . "</td>";

    echo "</tr>";
     ?>
    

    </tbody>


<script src="../scripts/formBuscador.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</body>

</html>

