<tbody>
    <?php

    $consola = '';
    foreach ($juegos as $juego) {

        echo "<tr>";
        echo "<td>" . $juego->ID . "</td>";
        echo "<td>" . $juego->nombre . "</td>";
        echo "<td>" . $juego->fecha_lanzamiento . "</td>";
        echo "<td>" . $juego->jugadores . "</td>";
        ?>
        <td><a href="modificar/<?php echo $juego->ID ?>" class= "btn btn-small btn btn-warning"><i  class="fa-solid fa-pen"> </i> </a> </td>;
        <td><a href="deleteConsola/<?php echo $juego->ID ?> "class= "btn btn-small btn btn-danger" ><i  class="fa-solid fa-pen"> </i> </a> </td>;
        <?php

        echo "</tr>";


    }
    ?>




</tbody>
</table>

<script src="../scripts/formBuscador.js"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</body>

</html>