
    <?php

    $consola = '';
    foreach ($juegos as $juego) : ?>
        <tr>
            <td><?= $juego->ID; ?></td>
            <td><?= $juego->nombre; ?></td>
            <td><?= $juego->fecha_lanzamiento; ?></td>
            <td><?= $juego->jugadores; ?></td>
           
           
        </tr>
    <?php endforeach; ?>




</tbody>
</table>

<script src="../scripts/formBuscador.js"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</body>

</html>