
<table class="table">
    
    <thead>
    <tr>
        <th scope="col" style="padding: 20px; "><h2>ID</h2></th>
        <th scope="col" style="padding: 20px;"><h2>nombre</h2></th>
        <th scope="col" style="padding: 20px;"><h2>jugadores</h2></th>
        <th scope="col" style="padding: 20px;"><h2>fecha de lanzamiento</h2></th>
        <th scope="col" style="padding: 20px;"><h2>consola</h2></th>
        
    </tr>
    </thead>

