<tbody>
      <tr>
        <td style="text-align: center;"><h4><?php echo $juego->ID?></h4></td>
        <td style="text-align: center;"><h4><?php echo $juego->nombre?></h4></td>
        <td style="text-align: center;"><h4><?php echo $juego->jugadores?></h4></td>
        <td style="text-align: center;"><h4><?php echo $juego->fecha_lanzamiento?></h4></td>
        <td style="text-align: center;"><h4><?php echo $consola->nombre?></h4></td>
      </tr>
