<form action="addConsola" method="POST">

    <input type="text" name="nombre" placeholder="insertar nombre de consola">
    <input type="text" name="marca" placeholder="insertar marca de consola">
    <input type="text" name="color" placeholder="insertar color de consola">
    <input type="text" name="generacion" placeholder="insertar generacion de consola">

    <button type="submit">agregar</button>

</form>