<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
<nav style="display: flex; gap: 20px;">
    <ul style="display: flex;">
        <li><a href="home">home</a></li>
        
        <ul class="dropdown-menu">
            <li><a href="catalogo">catalogo</a></li>
            <li><a href="juego">buscar juego</a></li>
            <li><a href="categorias">categorias</a></li> 
            <li><a href="categoria">categoria especifica</a></li>
        </ul>

        <ul class="dropdown-menu">
            <li><a href="addJuego">agregar juego</a></li>
            <li><a href="addConsola">agregar consola</a></li>
            <li><a href="updateConsola">modificar consola</a></li>
            <li><a href="updateJuego">modificar juego</a></li></ul>
        </ul>
    </ul>

</nav>
