
    <table class="table">
    
    <thead>
    <tr>
        <th scope="col" style="padding: 20px; "><h2>ID</h2></th>
        <th scope="col" style="padding: 20px;"><h2>nombre</h2></th>
        <th scope="col" style="padding: 20px;"><h2>jugadores</h2></th>
        <th scope="col" style="padding: 20px;"><h2>fecha de lanzamiento</h2></th>
        <th scope="col" style="padding: 20px;"><h2>consola</h2></th>
    </tr>
    </thead>

<?php foreach($juegos as $juego):?>

    <tbody>
      <tr>
        <td style="text-align: center;"><h4><?php echo $juego->ID?></h4></td>
        <td style="text-align: center;"><h4><?php echo $juego->nombre?></h4></td>
        <td style="text-align: center;"><h4><?php echo $juego->jugadores?></h4></td>
        <td style="text-align: center;"><h4><?php echo $juego->fecha_lanzamiento?></h4></td>
        <td style="text-align: center;"><h4><?php echo $juego->ID_consola?></h4></td>
      </tr>
    
<?php endforeach ?>
</tbody>
</table>